.\" Manpage for food_tracker
.\" Contact thorsten.johannvorderbrueggen@t-online.de to correct errors or typos.
.TH food_tracker 1 "01 Okt 2018" "0.0.1" "food_tracker man page"
.SH NAME
food_tracker
\-\- the food_tracker
.SH SYNOPSIS
.PP
.SH DESCRIPTION
This small tool is a simple
.BR food_tracker
(https://github.com/tjohann/food_tracker)
.PP
A simple Food-Tracker
.PP
.SH FILES
.BR food_tracker.c
\- main function
.br
.BR libfood_tracker.h
\- interface header
.br
.PP
.SH OPTIONS
None
.PP
.SH BUGS
No known bugs
.PP
.SH "SEE ALSO"
.BR libfood_tracker(3)
.PP
.SH AUTHOR
Thorsten Johannvorderbrueggen
.br
Email: \fB<thorsten.johannvorderbrueggen@t-online.de> \fP
